// src/types/collectionRecord.ts
export enum ConnectionStatus {
  CONNECTED = 'connected',
  NO_ANSWER = 'no_answer',
  WRONG_NUMBER = 'wrong_number',
}

export enum WillingnessToPay {
  HIGH = 'high',
  MEDIUM = 'medium',
  LOW = 'low',
  REFUSAL = 'refusal',
}

export interface CollectionRecord {
  id: number;
  loan_id: number;
  collector_id: number;
  mark: string;
  record_content: string;
  contact: string;
  target_contact: string;
  connection: ConnectionStatus;
  willingness_to_pay: WillingnessToPay;
  overdue_reason: string;
  result: string;
  record_time: string; // ISO string
  created_at: string; // Auto-generated by Supabase
  updated_at: string; // Auto-generated by Supabase
}

// Types pour les opérations CRUD
export type CreateCollectionRecordInput = Omit<
  CollectionRecord,
  'id' | 'created_at' | 'updated_at'
>;
export type UpdateCollectionRecordInput = Partial<
  Omit<CollectionRecord, 'id' | 'created_at' | 'loan_id' | 'collector_id'>
>;

// Types pour les relations
export type CollectionRecordWithRelations = CollectionRecord & {
  loan?: {
    id: number;
    loan_number: string;
    customer?: {
      id: number;
      name: string;
      mobile: string;
    };
  };
  collector?: {
    id: number;
    name: string;
    work_number: string;
  };
};

// Type pour les statistiques d'appel
export type CallStats = {
  total_calls: number;
  connected_calls: number;
  connection_rate: number;
  average_call_duration: number; // En minutes
  promises_to_pay: number;
  refusal_count: number;
};
