// src/types/loan.ts
export interface Loan {
  id: number;
  loan_number: string;
  loan_order_number: string;
  product_name: string;
  customer_id: number;
  loan_amount: number;
  loan_tenure: number;
  loan_type: string;
  due_date: string; // ISO string
  app_status: string;
  app_channel: string;
  app_version: string;
  app_name: string;
  collector_id?: number | null;
  collection_stage?: string | null;
  days_overdue?: number | null;
  total_repayment?: number | null;
  amount_repaid?: number | null;
  tag?: string | null;
  repeated_borrowing: boolean;
  loan_status: string;
  created_at: string; // Auto-generated by Supabase
  updated_at: string; // Auto-generated by Supabase
}

// Types pour les opérations CRUD
export type CreateLoanInput = Omit<Loan, 'id' | 'created_at' | 'updated_at'>;
export type UpdateLoanInput = Partial<
  Omit<Loan, 'id' | 'created_at' | 'loan_number' | 'customer_id'>
>;

// Types pour les relations
export type LoanWithRelations = Loan & {
  customer?: {
    id: number;
    name: string;
    mobile: string;
  };
  collector?: {
    id: number;
    name: string;
    work_number: string;
  };
  collection_records?: Array<{
    id: number;
    record_time: string;
    result: string;
  }>;
  repayments?: Array<{
    id: number;
    repayment_amount: number;
    trading_status: string;
  }>;
};

// Type pour les statistiques de prêt
export type LoanStats = {
  total_loans: number;
  total_amount: number;
  average_loan_amount: number;
  overdue_loans: number;
  repayment_rate: number;
};
