import { useConfig } from '@creditwave/hooks';
import { Card } from '../card';
import { TextLine } from '../text-line';

enum ConnectionStatus {
  CONNECTED = 'connected',
  NO_ANSWER = 'no_answer',
  WRONG_NUMBER = 'wrong_number',
}

enum WillingnessToPay {
  HIGH = 'high',
  REFUSAL = 'refusal',
}

export type CollectionRecordProps = {
  id: number;
  loan_id: number;
  collector_id: number;
  mark: string;
  record_content: string;
  contact: string;
  target_contact: string;
  connection: ConnectionStatus;
  willingness_to_pay: WillingnessToPay;
  overdue_reason: string;
  result: string;
  record_time: string; // ISO string
  created_at: string; // Auto-generated by Supabase
  updated_at: string; // Auto-generated by Supabase
};

export function CollectionRecord({ ...item }: CollectionRecordProps) {
  const { theme } = useConfig();

  return (
    <Card
      style={({ pressed }) => [
        {
          gap: 4,
          paddingVertical: 12,
          paddingHorizontal: 12,
          marginHorizontal: -12,
        },
        pressed && { backgroundColor: theme.primary + '22' },
      ]}
    >
      <TextLine
        label="Connection"
        value={
          {
            connected: 'Connected',
            no_answer: 'No answer',
            wrong_number: 'Wrong number',
          }[item.connection]
        }
      />

      <TextLine
        label="Willingness to pay"
        value={
          {
            high: 'Yes',
            refusal: 'No',
          }[item.willingness_to_pay]
        }
      />

      <TextLine label="Contact target" value={item.target_contact} />

      <TextLine label="Remark" value={item.mark} />
    </Card>
  );
}
